### ISSUE TITLE
Eth2 Renaming

### ISSUE THREAD

**Issue by taxmeifyoucan** [eth-clients/eth2-networks#64]
To avoid confusion about different technical notions on what Eth2 is, I suggest renaming `eth2` to `consensus` or `beacon-chain`. Repository is full of references to Eth2, at least name of the repo and readme could reflect this.

**Comment by arnetheduck** [comment]
There's lack of consensus around `consensus` as far as naming goes, with the merge coming up - we're waiting for the dust to settle on this debate as renames are painful and break links - maybe it can simply be called `eth-networks` and we can include eth1-networks as well here.

**Comment by djrtwo** [comment]
Yeah, I would love to unify this as a place for merge networks and beyond and if we do that, the "eth2" (or "consensus") name is no longer apt.

With it's current name and contents, it's not necessarily even clear if merge devnets should go in here *or* how they should be represented in here. cc @parithosh

**Comment by parithosh** [comment]
I'd suggest creating a new repo under the `ethereum` org called `eth-networks`. The main repo can contain `execution-testnets`, `consensus-testnets` and `merge-testnets` as the folder structure. I'd migrate the entire contents of this repo under the `consensus-testnets`. New merge testnet info can then go under `merge-testnets` and we can depricate using this repo in the future. 

Would this be an acceptible path forward?

**Comment by mratsim** [comment]
I think a different organization `eth-clients` is still valuable. We don't want to burden the Ethereum Foundation with something that needs significantly more coordination and admin on the client team side at times (just before a new testnet).

**Comment by parithosh** [comment]
Agreed, I'll create an `eth-clients` org and we can add people to manage the org. I'll create a `testnet-configs` repo under that to store the configs.

**Comment by arnetheduck** [comment]
... or we can simply rename this org - it doesn't have a purpose, beyond this

**Comment by parithosh** [comment]
Org has been renamed to `eth-clients`. Merge configs are in `merge-testnets` and eth2 tesnets are in `eth2-networks`. I'd say things are well named for now.
